set echo on
set serverout on
DECLARE
  v_blob BLOB;
  v_opt PLS_INTEGER;
BEGIN
  SELECT image INTO v_blob FROM secure_data WHERE ROWNUM = 1 FOR UPDATE;
  v_opt := DBMS_LOB.GETOPTIONS(v_blob, DBMS_LOB.OPT_COMPRESS);
  DBMS_OUTPUT.PUT_LINE( CASE v_opt WHEN DBMS_LOB.COMPRESS_ON THEN 'COMPRESS ON' ELSE 'COMPRESS OFF' END);
  DBMS_LOB.SETOPTIONS(v_blob, DBMS_LOB.OPT_COMPRESS, DBMS_LOB.COMPRESS_OFF);
  v_opt := DBMS_LOB.GETOPTIONS(v_blob, DBMS_LOB.OPT_COMPRESS);
  DBMS_OUTPUT.PUT_LINE( CASE v_opt WHEN DBMS_LOB.COMPRESS_ON THEN 'COMPRESS ON' ELSE 'COMPRESS OFF' END);
  COMMIT;
END;
/
